### PR TITLE
removing deprecations for atom editor update. should solve issues #14…

### PR DESCRIPTION
**Pull request by cjwilburn**
… and #17 - #26

solves #14, #17, #18, #19, #20, #21, #22, #23, #24, #25, #26.

### CODE REVIEW

**Comment by lierdakil** [comment]
That's a dup of #13, and @jroesch seems to me MIA, since I couldn't reach him by e-mail or otherwise. Since May is nearly at its end, it might be a good idea to try contacting @jroesch directly (maybe you'll have better luck than me), or @benogle to discuss language-scala deprecation plan.

**Comment by cjwilburn** [comment]
Whoops! I totally wouldn't have bothered had I seen #13. I'll try to get in touch with the maintainers. Hopefully we'll all hear something soon.

**Comment by mcous** [comment]
Technically #13 is a dupe of #12 :smiley:

But yeah I gave up on waiting for this package and have been using [my own fork](https://github.com/mcous/language-scala) since.

**Comment by lierdakil** [comment]
@mcous, if you'd be interested in maintaining this package, I advise you express your interest in #28. To my knowledge, there has been a little holdup with transferring package ownership to atom-community, so you still have a chance to take over, if you want.

**Comment by gangstead** [comment]
New collaborators added to liven up the place.  I merged the other one.

**Pull request closed without merging**
